# Generated by Django 2.2.12 on 2021-03-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
            ],
        ),
    ]
